---
title: "Topics and Articles of Interest"
author: "Brandon Loudermilk"
date: "November 11, 2015"
output: html_document
---

Please list any topics and articles that are of interest. If you see a topic here you like, then go find and article on it and present it to the group.

## Future Topics
 * Convolutional Neural Networks, Deep Learning
 * One-class Classification, Anomaly Detection
 * Time series analysis, change point detection
 * TensorFlow
 * Useful public data sets ( UCI datasets such as Adult dataset)
 * Engineering (version control, TDD, functional programming, OOA&D)
 * R/Python packages for data science
 * Data Visualization, UI, UX
 * Tools, Jupyter, Shiny, RStudio
 * Differences between lapply, sapply, tapply, rapply,mapply and apply
 * Discussion of Claude Shannon's seminal paper on Entropy in 1948 
 * Some future journal papers on retailing ( althought they are somewhat specific )

Sirohi, N., Mclaughlin, E. W., & Wittink, D. R. (1998). A model of consumer
perceptions and store loyalty intentions for a supermarket retailer. 
Journal of Retailing, 74 (2), 223-245.

Summers, T. A., Belleau, B. D., & Wozniak, P. J. (1992). Fashion and shopping
perceptions, demographics, and store patronage. 
Clothing and Textiles Research Journal, 11 (19), 83-91.

Summers, T. A., & Wozniak, P. J. (1990, Spring). Discount store patronage preferences
of rural and urban women.  Clothing and Textile Research Journal, 8 (3), 1-6.
